Added filter for adding X-Request-ID to requests
NHSDigital/summary-care-record-api pull request #59
Opened 2020-11-23 14:22 UTC by ElliotB-96

## Summary
* Routine Change
* :exclamation: Breaking Change
* :robot: Operational or Infrastructure Change
* :sparkles: New Feature
* :warning: Potential issues that might be caused by this change

Add any other relevant notes or explanations here. **Remove this line if you have nothing to add.**

## Reviews Required
* [x] Dev
* [ ] Test
* [ ] Tech Author
* [ ] Product Owner

## Review Checklist
:information_source: This section is to be filled in by the **reviewer**.

* [ ] I have reviewed the changes in this PR and they fill all or part of the acceptance criteria of the ticket, and the code is in a mergeable state.
* [ ] If there were infrastructure, operational, or build changes, I have made sure there is sufficient evidence that the changes will work.
* [ ] I have ensured the changelog has been updated by the submitter, if necessary.

2020-11-23 16:31 UTC, Broom94 requested changes

2020-11-23 16:31 UTC, Broom94 commented on docker/service/src/main/java/uk/nhs/adaptors/scr/consts/HttpHeaders.java
> +    public static final String LOGGING_ID_HEADER = "X-Request-ID";
Change to Request_ID_LOGGER

2020-11-23 16:31 UTC, Broom94 commented on docker/service/src/main/java/uk/nhs/adaptors/scr/config/ExceptionHandlerFilter.java
> +    public void invalidResponse(HttpServletResponse response, String header_name)
Use more descriptive method name, createAndThrow or throwInvalidUUIDRespose

2020-11-23 16:31 UTC, Broom94 commented on docker/service/src/main/java/uk/nhs/adaptors/scr/config/ExceptionHandlerFilter.java
> +        var logging_id = request.getHeader(LOGGING_ID_HEADER);
camelCase these, rename with token at the end

2020-11-23 16:31 UTC, Broom94 commented on docker/service/src/main/java/uk/nhs/adaptors/scr/config/ExceptionHandlerFilter.java
> +        if (StringUtils.isNotEmpty(correlation_id) && !correlation_id.matches(UUID_REGEX)) {
Could this validation be extracted into a separate method?

2020-11-23 16:31 UTC, Broom94 commented on docker/service/src/main/java/uk/nhs/adaptors/scr/config/ExceptionHandlerFilter.java
> +    public void invalidResponse(HttpServletResponse response, String header_name)
camelCase header name

2020-11-23 16:31 UTC, Broom94 commented on docker/service/src/main/java/uk/nhs/adaptors/scr/config/LoggingIdFilterConfig.java
> +        registrationBean.setOrder(3);
magic no

2020-11-23 16:33 UTC, Broom94 commented
Good job so far p.s. update with master

2020-11-23 16:39 UTC, Broom94 commented on docker/service/src/main/java/uk/nhs/adaptors/scr/config/LoggingIdFilterConfig.java
> +        registrationBean.setOrder(3);
create const class

2020-11-23 17:17 UTC, Broom94 requested changes

2020-11-23 17:17 UTC, Broom94 commented on docker/service/src/main/java/uk/nhs/adaptors/scr/config/ConversationIdFilterConfig.java
> +
remove extra space, tip run format file on all classes your working on

2020-11-23 17:17 UTC, Broom94 commented on docker/service/src/main/java/uk/nhs/adaptors/scr/consts/Numbers.java
> +    public static final int THREE = 3;
rename these to reflect classes they're used in 

Something like, CORRELATION_ID_FILTER_ORDER

2020-11-24 09:53 UTC, bartek-sarul requested changes

2020-11-24 09:53 UTC, bartek-sarul commented on docker/service/src/main/java/uk/nhs/adaptors/scr/config/ExceptionHandlerFilter.java
> +    public boolean checkValidUUID(String header) {
If you check something, you would expect that it would return `False` if data is not correct. Here you return `True`

2020-11-24 09:53 UTC, bartek-sarul commented on docker/service/src/main/java/uk/nhs/adaptors/scr/config/ExceptionHandlerFilter.java
> +        if (checkValidUUID(correlationIdToken)) {
Should be expecting `False` not `True`

2020-11-24 09:53 UTC, bartek-sarul commented on docker/service/src/main/java/uk/nhs/adaptors/scr/config/ExceptionHandlerFilter.java
> +        } else if (checkValidUUID(loggingIdToken)) {
Should be expecting `False` not `True`

2020-11-24 09:53 UTC, bartek-sarul commented on docker/service/src/main/java/uk/nhs/adaptors/scr/config/LoggingIdFilter.java
> +public class LoggingIdFilter extends OncePerRequestFilter {
Rename to `RequestIdFilter`

2020-11-24 09:53 UTC, bartek-sarul commented on docker/service/src/main/java/uk/nhs/adaptors/scr/consts/RequestFiltersOrdering.java
> +    public static final int LOGGING_ID_FILTER_ORDER = 3;
Rename to `REQUEST_ID_FILTER_ORDER`

2020-11-24 10:17 UTC, bartek-sarul requested changes

2020-11-24 10:17 UTC, bartek-sarul commented on docker/service/src/main/java/uk/nhs/adaptors/scr/config/ExceptionHandlerFilter.java
> +        var loggingIdToken = request.getHeader(REQUEST_ID_LOGGER);
Should be `requestIdToken`

2020-11-24 10:17 UTC, bartek-sarul commented on docker/service/src/main/java/uk/nhs/adaptors/scr/config/RequestIdFilterConfig.java
> +    public FilterRegistrationBean<RequestIdFilter> servletRegistrationBeanForLoggingID() {
Rename to `...ForRequestID`

2020-11-24 11:39 UTC, bartek-sarul approved these changes

2020-12-01 08:50 UTC, Broom94 approved these changes

2020-12-01 08:50 UTC, merged